Metrics/LineLength:
  Max: 120
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    # TODO: fix this file
    - 'app/controllers/bookings_controller.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
