version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/vattentornet
    ports:
      - "3000:3000"
    depends_on:
      - db
  bundle:
    # Clever Bundler cache from http://bradgessler.com/articles/docker-bundler/
    image: vattentornet_web
    command: echo "I'm a little data container, short and stout..."
    volumes:
      - /bundle
